version: "3.4"
services:
  openethereum-gnosis-chain.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v3.3.3
    image: "openethereum-gnosis-chain.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
    volumes:
      - "data:/home/openethereum/.local/share"
    environment:
      - EXTRA_OPTS=
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
volumes:
  data: {}
